# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: spdkcsi-controller
  namespace: {{ .Release.Namespace }}
{{ include "spdk.labels" . | indent 2 }}
spec:
  serviceName: spdkcsi-controller
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: spdkcsi-controller
  template:
    metadata:
{{ include "spdk.labels" . | indent 6 }}
        app: spdkcsi-controller
    spec:
      serviceAccount: spdkcsi-controller-sa
      hostNetwork: true
      containers:
      - name: spdkcsi-provisioner
        image: "{{ .Values.image.csiProvisioner.repository }}:{{ .Values.image.csiProvisioner.tag }}"
        imagePullPolicy: {{ .Values.image.csiProvisioner.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=500ms"
        - "--leader-election=true"
        - "--leader-election-namespace={{ .Release.Namespace }}"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-controller
        image: "{{ .Values.image.spdkcsi.repository }}:{{ .Values.image.spdkcsi.tag }}"
        imagePullPolicy: {{ .Values.image.spdkcsi.pullPolicy }}
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi-provisioner.sock"
        - "--nodeid=$(NODE_ID)"
        - "--controller"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: spdkcsi-config
          mountPath: /etc/spdkcsi-config/
          readOnly: true
        - name: spdkcsi-secret
          mountPath: /etc/spdkcsi-secret/
          readOnly: true
      volumes:
      - name: socket-dir
        emptyDir:
          medium: "Memory"
      - name: spdkcsi-config
        configMap:
          name: spdkcsi-cm
      - name: spdkcsi-secret
        secret:
          secretName: spdkcsi-secret
