# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-nodeservercm
data:
  # xpu.targetType:
  #   - SMA: xpu-sma-nvmftcp, xpu-sma-virtioblk, xpu-sma-nvme
  # xpu.targetAddr:
  #   - URL to connect the xPU node through GRPC, IPADDR:PORT
  #   - 127.0.0.1:5114 for SMA server by default
  # kvmPciBridges:
  #   - used by sma-virtioblk, sma-nvme
  #   - based on the configuration in "deploy/spdk/sma.yaml" and qemu VM
  #
  # example:
  #  nodeserver-config.json: |-
  #  {
  #    "xpuList": [
  #      {
  #        "name": "xPU0",
  #        "targetType": "xpu-sma-nvmftcp",
  #        "targetAddr": "127.0.0.1:5114"
  #      }
  #    ],
  #    "kvmPciBridges": 2
  #  }
  nodeserver-config.json: |-
    {
      "xpuList": [],
      "kvmPciBridges": null
    }
