# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: Secret
metadata:
  name: spdkcsi-secret
stringData:
  # Specify node specific token with item "name" matches ConfigMap.
  # {
  #   "name": "spdk-testnode",
  #   "username": "myuser",
  #   "password": "mypass"
  # }
  secret.json: |-
    {
      "simplybk": {
        "secret": "VoiesgovuSPLzyUN94Di"
      }
    }
