# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spdkcsi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: spdkcsi-sc

---
kind: Pod
apiVersion: v1
metadata:
  name: spdkcsi-test
spec:
  containers:
  - name: alpine
    image: alpine:3
    imagePullPolicy: "IfNotPresent"
    command: ["sleep", "365d"]
    volumeMounts:
    - mountPath: "/spdkvol"
      name: spdk-volume
  volumes:
  - name: spdk-volume
    persistentVolumeClaim:
      claimName: spdkcsi-pvc
